edma_check.obj: ../edma_check.c
edma_check.obj: /opt/ti/C6000CGT7.4.0/include/stdio.h
edma_check.obj: /opt/ti/C6000CGT7.4.0/include/linkage.h
edma_check.obj: /opt/ti/C6000CGT7.4.0/include/stdarg.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Timestamp.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/std.h
edma_check.obj: /opt/ti/C6000CGT7.4.0/include/stdarg.h
edma_check.obj: /opt/ti/C6000CGT7.4.0/include/stddef.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/ti/targets/elf/std.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/ti/targets/elf/C66.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/ti/targets/std.h
edma_check.obj: /opt/ti/C6000CGT7.4.0/include/stdint.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/xdc.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types__prologue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/package/package.defs.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types__epilogue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/ITimestampClient.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Memory.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Error__prologue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/package/Main_Module_GateProxy.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IGateProvider.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Error__epilogue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/package/Memory_HeapProxy.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/ITimestampProvider.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/ITimestampClient.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/package/Timestamp_SupportProxy.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/ITimestampProvider.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/package/Timestamp_SupportProxy.h
edma_check.obj: ../edma.h
edma_check.obj: /opt/ti/edma3_lld_02_11_05_02/packages/ti/sdo/edma3/drv/sample/bios6_edma3_drv_sample.h
edma_check.obj: /opt/ti/C6000CGT7.4.0/include/stdio.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Semaphore.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/package/package.defs.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Clock.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Swi.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Diags__prologue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Diags__epilogue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Assert__prologue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Assert__epilogue.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Queue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Log__prologue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Main.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Text.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Log__epilogue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Queue.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/hal/Timer.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/hal/package/package.defs.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/interfaces/ITimer.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/interfaces/package/package.defs.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/hal/package/Timer_TimerProxy.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/interfaces/ITimer.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Task.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Task__prologue.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Clock.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/interfaces/ITaskSupport.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Error.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Queue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IHeap.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/package/Task_SupportProxy.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/interfaces/ITaskSupport.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Task__epilogue.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Event.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IInstance.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Event__prologue.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Clock.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Task.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Queue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Event__epilogue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Diags.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Assert.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/knl/Queue.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Log.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
edma_check.obj: /opt/ti/edma3_lld_02_11_05_02/packages/ti/sdo/edma3/drv/edma3_drv.h
edma_check.obj: /opt/ti/edma3_lld_02_11_05_02/packages/ti/sdo/edma3/rm/edma3_rm.h
edma_check.obj: /opt/ti/edma3_lld_02_11_05_02/packages/ti/sdo/edma3/rm/edma3_common.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/family/c66/Cache.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/family/c66/package/package.defs.h
edma_check.obj: /opt/ti/bios_6_33_05_46/packages/ti/sysbios/interfaces/ICache.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/Types.h
edma_check.obj: /opt/ti/xdctools_3_23_04_60/packages/xdc/runtime/IModule.h
