#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.elf.C66{1,0,7.4,0,2
#
edma3_drv_bios6_c6678_st_sample.xe66: package/cfg/edma3_drv_bios6_c6678_st_sample.xe66.mak

clean::
	-$(RM) package/cfg/edma3_drv_bios6_c6678_st_sample.xe66.mak
