BLAS Level 3: dataMoveStrsm.c File Reference
dataMoveStrsm.c File Reference
#include "string.h"
#include "dataMoveStrsm.h"
#include "defSC66.h"
Functions
void inverse4x4LowerS (real *restrict src, int ld, int flagDiagisU)
inverse4x4UpperS (real *restrict src, int ld, int flagDiagisU)
void arrangeDataUAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
void arrangeDataLTAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
void arrangeDataLAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
void arrangeDataUTAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Function Documentation
void inverse4x4LowerS (real *restrict src, int ld, int flagDiagisU)
Definition at line 44 of file dataMoveStrsm.c.
Referenced by arrangeDataLAStrsm(), and arrangeDataLTAStrsm().
inverse4x4UpperS (real *restrict src, int ld, int flagDiagisU)
Definition at line 115 of file dataMoveStrsm.c.
Referenced by arrangeDataUAStrsm(), and arrangeDataUTAStrsm().
Copyright 2012, Texas Instruments Incorporated