BLAS Level 3: dataMoveCtrsm.c File Reference
dataMoveCtrsm.c File Reference
#include "c6x.h"
#include "string.h"
#include "dataMoveCtrsm.h"
#include "defCC66.h"
Functions
void inverse2x2LowerC (complex *restrict src, int ld, int flagDiagisU)
inverse2x2Upper (complex *restrict src, int ld, int flagDiagisU)
void arrangeDataUACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
void arrangeDataLTACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
void arrangeDataLACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
void arrangeDataUTACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Function Documentation
void inverse2x2LowerC (complex *restrict src, int ld, int flagDiagisU)
Definition at line 45 of file dataMoveCtrsm.c.
Referenced by arrangeDataLACtrsm(), and arrangeDataLTACtrsm().
inverse2x2Upper (complex *restrict src, int ld, int flagDiagisU)
Definition at line 92 of file dataMoveCtrsm.c.
Referenced by arrangeDataUACtrsm(), and arrangeDataUTACtrsm().
Copyright 2012, Texas Instruments Incorporated