BLAS Level 3: dataMoveDtrsm.c File Reference
dataMoveDtrsm.c File Reference
#include "string.h"
#include "dataMoveDtrsm.h"
#include "defDC66.h"
Functions
void inverse4x4LowerD (double *restrict src, int ld, int flagDiagisU)
inverse4x4UpperD (double *restrict src, int ld, int flagDiagisU)
void arrangeDataUADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
void arrangeDataLTADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
void arrangeDataLADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
void arrangeDataUTADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Function Documentation
void inverse4x4LowerD (double *restrict src, int ld, int flagDiagisU)
Definition at line 44 of file dataMoveDtrsm.c.
Referenced by arrangeDataLADtrsm(), and arrangeDataLTADtrsm().
inverse4x4UpperD (double *restrict src, int ld, int flagDiagisU)
Definition at line 115 of file dataMoveDtrsm.c.
Referenced by arrangeDataUADtrsm(), and arrangeDataUTADtrsm().
Copyright 2012, Texas Instruments Incorporated