BLAS Level 3: test package
test package
Data Structures
struct _ParamsBlas3_
BLAS level 3 parameter structure. Refer to standard BLAS level 3 API for porper definitions.
Defines
#define MAX_LINE_LEN 100
#define dataType complex
#define baseType real
#define xsyrk_ csyrk_
#define xsyrk csyrkSC
#define testXsyrk testCsyrk
#define XSYRK "CSYRK"
#define M_KERNEL M_KERNEL_C
#define N_KERNEL N_KERNEL_C
#define ALPHACOMPLEX
#define BETACOMPLEX
#define dataType double
#define baseType double
#define xsyrk_ dsyrk_
#define xsyrk dsyrkSC
#define testXsyrk testDsyrk
#define XSYRK "DSYRK"
#define M_KERNEL M_KERNEL_D
#define N_KERNEL N_KERNEL_D
#define dataType real
#define baseType real
#define xsyrk_ ssyrk_
#define xsyrk ssyrkSC
#define testXsyrk testSsyrk
#define XSYRK "SSYRK"
#define M_KERNEL M_KERNEL_S
#define N_KERNEL N_KERNEL_S
#define dataType doublecomplex
#define baseType double
#define xsyrk_ zsyrk_
#define xsyrk zsyrkSC
#define testXsyrk testZsyrk
#define XSYRK "ZSYRK"
#define M_KERNEL M_KERNEL_Z
#define N_KERNEL N_KERNEL_Z
#define ALPHACOMPLEX
#define BETACOMPLEX
Typedefs
typedef struct _ParamsBlas3_ ParamsBlas3_t
BLAS level 3 parameter structure. Refer to standard BLAS level 3 API for porper definitions.
Functions
void readAPIparams (FILE *pFid, ParamsBlas3_t *pParam_s)
reads parameters from file
void writeAPIparams (FILE *pFid, ParamsBlas3_t *pParam_s)
write parameters from file along with some results
double compareSMatrices (int m, int n, real *a, int lda, real *b, int ldb)
find maximum absolute difference between two single precision matrices
double compareDMatrices (int m, int n, double *a, int lda, double *b, int ldb)
find maximum absolute difference between two double precision matrices
double compareCMatrices (int m, int n, complex *a, int lda, complex *b, int ldb)
find maximum absolute difference between two single precision complex matrices
double compareZMatrices (int m, int n, doublecomplex *a, int lda, doublecomplex *b, int ldb)
find maximum absolute difference between two double precision complex matrices
void randomSFill (real *a, int len)
randomly fill memory area with single precision values
void randomDFill (double *a, int len)
randomly fill memory area with double precision values
void randomCFill (complex *a, int len)
randomly fill memory area with single precision complex values
void randomZFill (doublecomplex *a, int len)
randomly fill memory area with double precision complex values
void testCgemm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for cgemm functionality
void testDgemm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for sgemm functionality
void testSgemm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for sgemm functionality
void testZgemm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for zgemm functionality
void testChemm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for chemm functionality
void testZhemm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for zhemm functionality
void testCher2k (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for cher2k functionality
void testZher2k (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for zher2k functionality
void testCherk (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for cherk functionality
void testZherk (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for zherk functionality
void testCsymm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for csymm functionality
void testDsymm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for dsymm functionality
void testSsymm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for ssymm functionality
void testZsymm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for zsymm functionality
void testCsyr2k (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for csyr2k functionality
void testDsyr2k (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for dsyr2k functionality
void testSsyr2k (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for ssyr2k functionality
void testZsyr2k (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for zsyr2k functionality
void testCsyrk (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for csyrk functionality
void testDsyrk (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for dsyrk functionality
void testSsyrk (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for ssyrk functionality
void testZsyrk (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for zsyrk functionality
void testCtrmm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for ctrmm functionality
void testDtrmm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for dtrmm functionality
void testStrmm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for strmm functionality
void testZtrmm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for ztrmm functionality
void testCtrsm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for ctrsm functionality
void testDtrsm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for dtrsm functionality
void testStrsm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for strsm functionality
void testZtrsm (ParamsBlas3_t *pParams, double *gFlops, double *err)
main test API for ztrsm functionality
Define Documentation
#define ALPHACOMPLEX
Definition at line 84 of file testCsyrk.c.
#define ALPHACOMPLEX
Definition at line 84 of file testZsyrk.c.
#define baseType real
Definition at line 66 of file testCsyrk.c.
#define baseType real
Definition at line 66 of file testSsyrk.c.
#define baseType double
Definition at line 66 of file testDsyrk.c.
#define baseType double
Definition at line 66 of file testZsyrk.c.
#define BETACOMPLEX
Definition at line 88 of file testZsyrk.c.
#define BETACOMPLEX
Definition at line 88 of file testCsyrk.c.
#define dataType real
Definition at line 65 of file testSsyrk.c.
#define dataType complex
Definition at line 65 of file testCsyrk.c.
#define dataType double
Definition at line 65 of file testDsyrk.c.
#define dataType doublecomplex
Definition at line 65 of file testZsyrk.c.
#define M_KERNEL M_KERNEL_Z
Definition at line 80 of file testZsyrk.c.
#define M_KERNEL M_KERNEL_D
Definition at line 80 of file testDsyrk.c.
#define M_KERNEL M_KERNEL_C
Definition at line 80 of file testCsyrk.c.
#define M_KERNEL M_KERNEL_S
Definition at line 80 of file testSsyrk.c.
#define MAX_LINE_LEN 100
Definition at line 52 of file paramBlas3.h.
Referenced by readAPIparams(), and testLoop().
#define N_KERNEL N_KERNEL_Z
Definition at line 81 of file testZsyrk.c.
#define N_KERNEL N_KERNEL_D
Definition at line 81 of file testDsyrk.c.
#define N_KERNEL N_KERNEL_C
Definition at line 81 of file testCsyrk.c.
#define N_KERNEL N_KERNEL_S
Definition at line 81 of file testSsyrk.c.
#define testXsyrk testSsyrk
Definition at line 74 of file testSsyrk.c.
#define testXsyrk testZsyrk
Definition at line 74 of file testZsyrk.c.
#define testXsyrk testDsyrk
Definition at line 74 of file testDsyrk.c.
#define testXsyrk testCsyrk
Definition at line 74 of file testCsyrk.c.
#define xsyrk dsyrkSC
Definition at line 71 of file testDsyrk.c.
#define XSYRK "ZSYRK"
Definition at line 75 of file testZsyrk.c.
#define xsyrk zsyrkSC
Definition at line 71 of file testZsyrk.c.
#define xsyrk csyrkSC
Definition at line 71 of file testCsyrk.c.
#define XSYRK "SSYRK"
Definition at line 75 of file testSsyrk.c.
#define xsyrk ssyrkSC
Definition at line 71 of file testSsyrk.c.
#define XSYRK "DSYRK"
Definition at line 75 of file testDsyrk.c.
#define XSYRK "CSYRK"
Definition at line 75 of file testCsyrk.c.
#define xsyrk_ zsyrk_
Definition at line 67 of file testZsyrk.c.
#define xsyrk_ dsyrk_
Definition at line 67 of file testDsyrk.c.
#define xsyrk_ ssyrk_
Definition at line 67 of file testSsyrk.c.
#define xsyrk_ csyrk_
Definition at line 67 of file testCsyrk.c.
Typedef Documentation
typedef struct _ParamsBlas3_ ParamsBlas3_t
BLAS level 3 parameter structure. Refer to standard BLAS level 3 API for porper definitions.
Function Documentation
double compareCMatrices (int m, int n, complex * a, int lda, complex * b, int ldb)
find maximum absolute difference between two single precision complex matrices
Parameters:
[in] m number of rows to compare
[in] n number of cols to compare
[in] a pointer to first matrix
[in] lda first dimension of matrix a
[in] b pointer to second matrix
[in] ldb first dimension of matrix b
Returns:
returns maximum absolute error
Definition at line 90 of file testUtil.c.
double compareDMatrices (int m, int n, double * a, int lda, double * b, int ldb)
find maximum absolute difference between two double precision matrices
Parameters:
[in] m number of rows to compare
[in] n number of cols to compare
[in] a pointer to first matrix
[in] lda first dimension of matrix a
[in] b pointer to second matrix
[in] ldb first dimension of matrix b
Returns:
returns maximum absolute error
Definition at line 67 of file testUtil.c.
double compareSMatrices (int m, int n, real * a, int lda, real * b, int ldb)
find maximum absolute difference between two single precision matrices
Parameters:
[in] m number of rows to compare
[in] n number of cols to compare
[in] a pointer to first matrix
[in] lda first dimension of matrix a
[in] b pointer to second matrix
[in] ldb first dimension of matrix b
Returns:
returns maximum absolute error
Definition at line 44 of file testUtil.c.
double compareZMatrices (int m, int n, doublecomplex * a, int lda, doublecomplex * b, int ldb)
find maximum absolute difference between two double precision complex matrices
Parameters:
[in] m number of rows to compare
[in] n number of cols to compare
[in] a pointer to first matrix
[in] lda first dimension of matrix a
[in] b pointer to second matrix
[in] ldb first dimension of matrix b
Returns:
returns maximum absolute error
Definition at line 121 of file testUtil.c.
void randomCFill (complex * a, int len)
randomly fill memory area with single precision complex values
Parameters:
[in] a pointer to area to fill
[in] len number of elements to fill
Definition at line 176 of file testUtil.c.
References complex::i, and complex::r.
void randomDFill (double * a, int len)
randomly fill memory area with double precision values
Parameters:
[in] a pointer to area to fill
[in] len number of elements to fill
Definition at line 164 of file testUtil.c.
void randomSFill (real * a, int len)
randomly fill memory area with single precision values
Parameters:
[in] a pointer to area to fill
[in] len number of elements to fill
Definition at line 152 of file testUtil.c.
void randomZFill (doublecomplex * a, int len)
randomly fill memory area with double precision complex values
Parameters:
[in] a pointer to area to fill
[in] len number of elements to fill
Definition at line 189 of file testUtil.c.
References doublecomplex::i, and doublecomplex::r.
void readAPIparams (FILE * pFid, ParamsBlas3_t * pParam_s)
reads parameters from file
Parameters:
[in] pFid file containing parameters
[in] pParam_s Pointer to BLAS3 parameter structure
Definition at line 49 of file paramBlas3.c.
References _ParamsBlas3_::alpha, _ParamsBlas3_::alpha_i, _ParamsBlas3_::beta, _ParamsBlas3_::beta_i, _ParamsBlas3_::blas3Api, _ParamsBlas3_::diag, _ParamsBlas3_::k, _ParamsBlas3_::m, MAX_LINE_LEN, _ParamsBlas3_::n, paramSt, _ParamsBlas3_::side, sLine, _ParamsBlas3_::trans, _ParamsBlas3_::transa, _ParamsBlas3_::transb, and _ParamsBlas3_::uplo.
Referenced by testLoop().
void testCgemm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for cgemm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testChemm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for chemm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testCher2k (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for cher2k functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testCherk (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for cherk functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testCsymm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for csymm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testCsyr2k (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for csyr2k functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testCsyrk (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for csyrk functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testCtrmm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for ctrmm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testCtrsm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for ctrsm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testDgemm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for sgemm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testDsymm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for dsymm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testDsyr2k (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for dsyr2k functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testDsyrk (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for dsyrk functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testDtrmm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for dtrmm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testDtrsm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for dtrsm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testSgemm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for sgemm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testSsymm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for ssymm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testSsyr2k (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for ssyr2k functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testSsyrk (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for ssyrk functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testStrmm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for strmm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testStrsm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for strsm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testZgemm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for zgemm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testZhemm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for zhemm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testZher2k (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for zher2k functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testZherk (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for zherk functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testZsymm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for zsymm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testZsyr2k (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for zsyr2k functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testZsyrk (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for zsyrk functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testZtrmm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for ztrmm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void testZtrsm (ParamsBlas3_t * pParams, double * gFlops, double * err)
main test API for ztrsm functionality
Parameters:
[in] pParams test parameters
[out] gFlops computed GFLOPS
[out] err computed maximum absolute error between reference and optimized code (if VERIFICATION is used)
Referenced by testLoop().
void writeAPIparams (FILE * pFid, ParamsBlas3_t * pParam_s)
write parameters from file along with some results
Parameters:
[in] pFid file id to write to
[in] pParam_s Pointer to BLAS3 parameter structure
Definition at line 162 of file paramBlas3.c.
References _ParamsBlas3_::alpha, _ParamsBlas3_::alpha_i, _ParamsBlas3_::beta, _ParamsBlas3_::beta_i, _ParamsBlas3_::blas3Api, _ParamsBlas3_::diag, _ParamsBlas3_::k, _ParamsBlas3_::m, _ParamsBlas3_::n, _ParamsBlas3_::side, _ParamsBlas3_::trans, _ParamsBlas3_::transa, _ParamsBlas3_::transb, and _ParamsBlas3_::uplo.
Referenced by testLoop().
Copyright 2012, Texas Instruments Incorporated