BLAS Level 3: dataMove
dataMove
Functions
void dataMoveBHCgemm (complex *restrict dst, complex *restrict src, int k)
Move and re-arrange B-Hermitian as needed by kernel for cgemm. src point to B-Hermitian. dst will have B arranged in 4 x k (column major)
void dataMoveBTCgemm (complex *restrict dst, complex *restrict src, int k)
Move and re-arrange B' as needed by kernel for cgemm. src point to B'. dst will have B arranged in 4 x k (column major)
void dataMoveBCgemm (complex *restrict dst, complex *restrict src, int k)
Move and re-arrange B as needed by kernel for cgemm. src point to B. dst will have B arranged in 4 x k (column major)
void dataMoveACgemm (complex *restrict dst, complex *restrict src, int m, int k, int mPartition)
Move and re-arrange A as needed by kernel for cgemm. src point to A. dst will have blocks of A, each block arranged in 4 x k (column major)
void dataMoveATCgemm (complex *restrict dst, complex *restrict src, int m, int k, int kPartition)
Move and re-arrange A' as needed by kernel for cgemm. src point to A'. dst will have blocks of A, each block arranged in 4 x k (column major)
void dataMoveAHCgemm (complex *restrict dst, complex *restrict src, int m, int k, int kPartition)
Move and re-arrange A-Hermitian as needed by kernel for cgemm. src point to A-Hermitian. dst will have blocks of A, each block arranged in 4 x k (column major)
void dataMoveLChemm (complex *restrict src, int m, int ld)
Flip a lower triangular to create Hermitian upper part.
void dataMoveUChemm (complex *restrict src, int m, int ld)
MFlip an upper triangular to create Hermitian lower part.
void dataMoveLCsymm (complex *restrict src, int m, int ld)
Flip a lower triangular to create symmetric upper part.
void dataMoveUCsymm (complex *restrict src, int m, int ld)
MFlip an upper triangular to create symmetric lower part.
void arrangeDataUACtrmm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
void arrangeDataLTACtrmm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
void arrangeDataLACtrmm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
void arrangeDataUTACtrmm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
void arrangeDataUACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
void arrangeDataLTACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
void arrangeDataLACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
void arrangeDataUTACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
void dataMoveBTDgemm (double *restrict dst, double *restrict src, int k)
Move and re-arrange B' as needed by kernel for dgemm. src point to B'. dst will have B arranged in 4 x k (column major)
void dataMoveBDgemm (double *restrict dst, double *restrict src, int k)
Move and re-arrange B as needed by kernel for dgemm. src point to B. dst will have B arranged in 4 x k (column major)
void dataMoveADgemm (double *restrict dst, double *restrict src, int m, int k, int mPartition)
Move and re-arrange A as needed by kernel for dgemm. src point to A. dst will have blocks of A, each block arranged in 4 x k (column major)
void dataMoveATDgemm (double *restrict dst, double *restrict src, int m, int k, int kPartition)
Move and re-arrange A' as needed by kernel for dgemm. src point to A'. dst will have blocks of A, each block arranged in 4 x k (column major)
void dataMoveLDsymm (double *restrict src, int m, int ld)
Flip a lower triangular to create symmetric upper part.
void dataMoveUDsymm (double *restrict src, int m, int ld)
MFlip an upper triangular to create symmetric lower part.
void arrangeDataUADtrmm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
void arrangeDataLTADtrmm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
void arrangeDataLADtrmm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
void arrangeDataUTADtrmm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
void arrangeDataUADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
void arrangeDataLTADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
void arrangeDataLADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
void arrangeDataUTADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
void dataMoveBTSgemm (real *restrict dst, real *restrict src, int k)
Move and re-arrange B' as needed by kernel for sgemm. src point to B'. dst will have B arranged in 8 x k (column major)
void dataMoveBSgemm (real *restrict dst, real *restrict src, int k)
Move and re-arrange B as needed by kernel for sgemm. src point to B. dst will have B arranged in 8 x k (column major)
void dataMoveASgemm (real *restrict dst, real *restrict src, int m, int k, int mPartition)
Move and re-arrange A as needed by kernel for sgemm. src point to A. dst will have blocks of A, each block arranged in 4 x k (column major)
void dataMoveATSgemm (real *restrict dst, real *restrict src, int m, int k, int kPartition)
Move and re-arrange A' as needed by kernel for sgemm. src point to A'. dst will have blocks of A, each block arranged in 4 x k (column major)
void dataMoveLSsymm (real *restrict src, int m, int ld)
Flip a lower triangular to create symmetric upper part.
void dataMoveUSsymm (real *restrict src, int m, int ld)
MFlip an upper triangular to create symmetric lower part.
void arrangeDataUAStrmm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
void arrangeDataLTAStrmm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
void arrangeDataLAStrmm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
void arrangeDataUTAStrmm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
void arrangeDataUAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
void arrangeDataLTAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
void arrangeDataLAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
void arrangeDataUTAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
void dataMoveBHZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int k)
Move and re-arrange B-Hermitian as needed by kernel for zgemm. src point to B-Hermitian. dst will have B arranged in 2 x k (column major)
void dataMoveBTZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int k)
Move and re-arrange B' as needed by kernel for zgemm. src point to B'. dst will have B arranged in 2 x k (column major)
void dataMoveBZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int k)
Move and re-arrange B as needed by kernel for zgemm. src point to B. dst will have B arranged in 2 x k (column major)
void dataMoveAZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int m, int k, int mPartition)
Move and re-arrange A as needed by kernel for zgemm. src point to A. dst will have blocks of A, each block arranged in 2 x k (column major)
void dataMoveATZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int m, int k, int kPartition)
Move and re-arrange A' as needed by kernel for zgemm. src point to A'. dst will have blocks of A, each block arranged in 2 x k (column major)
void dataMoveAHZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int m, int k, int kPartition)
Move and re-arrange A-Hermitian as needed by kernel for zgemm. src point to A-Hermitian. dst will have blocks of A, each block arranged in 2 x k (column major)
void dataMoveLZhemm (doublecomplex *restrict src, int m, int ld)
Flip a lower triangular to create Hermitian upper part.
void dataMoveUZhemm (doublecomplex *restrict src, int m, int ld)
MFlip an upper triangular to create Hermitian lower part.
void dataMoveLZsymm (doublecomplex *restrict src, int m, int ld)
Flip a lower triangular to create symmetric upper part.
void dataMoveUZsymm (doublecomplex *restrict src, int m, int ld)
MFlip an upper triangular to create symmetric lower part.
void arrangeDataUAZtrmm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
void arrangeDataLTAZtrmm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
void arrangeDataLAZtrmm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
void arrangeDataUTAZtrmm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
void arrangeDataUAZtrsm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
void arrangeDataLTAZtrsm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
void arrangeDataLAZtrsm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
void arrangeDataUTAZtrsm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Function Documentation
void arrangeDataLACtrmm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 143 of file dataMoveCtrmm.c.
References MPARTITION_C.
void arrangeDataLACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 221 of file dataMoveCtrsm.c.
References inverse2x2LowerC(), M_KERNEL_C, and MPARTITION_C.
void arrangeDataLADtrmm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 137 of file dataMoveDtrmm.c.
References MPARTITION_D.
void arrangeDataLADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 266 of file dataMoveDtrsm.c.
References inverse4x4LowerD(), M_KERNEL_D, and MPARTITION_D.
void arrangeDataLAStrmm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 137 of file dataMoveStrmm.c.
References MPARTITION_S.
void arrangeDataLAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 266 of file dataMoveStrsm.c.
References inverse4x4LowerS(), M_KERNEL_S, and MPARTITION_S.
void arrangeDataLAZtrmm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 143 of file dataMoveZtrmm.c.
References MPARTITION_Z.
void arrangeDataLAZtrsm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 153 of file dataMoveZtrsm.c.
References M_KERNEL_Z, and MPARTITION_Z.
void arrangeDataLTACtrmm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 94 of file dataMoveCtrmm.c.
References KPARTITION_C.
void arrangeDataLTACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 180 of file dataMoveCtrsm.c.
References inverse2x2LowerC(), KPARTITION_C, and M_KERNEL_C.
void arrangeDataLTADtrmm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 90 of file dataMoveDtrmm.c.
References KPARTITION_D.
void arrangeDataLTADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 225 of file dataMoveDtrsm.c.
References inverse4x4LowerD(), KPARTITION_D, and M_KERNEL_D.
void arrangeDataLTAStrmm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 90 of file dataMoveStrmm.c.
References KPARTITION_S.
void arrangeDataLTAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 225 of file dataMoveStrsm.c.
References inverse4x4LowerS(), KPARTITION_S, and M_KERNEL_S.
void arrangeDataLTAZtrmm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 94 of file dataMoveZtrmm.c.
References KPARTITION_Z.
void arrangeDataLTAZtrsm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size KPARTITION by MPARTITION) for lower triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for lower triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 98 of file dataMoveZtrsm.c.
References KPARTITION_Z, and M_KERNEL_Z.
void arrangeDataUACtrmm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 45 of file dataMoveCtrmm.c.
References MPARTITION_C.
void arrangeDataUACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 139 of file dataMoveCtrsm.c.
References inverse2x2Upper(), M_KERNEL_C, and MPARTITION_C.
void arrangeDataUADtrmm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 43 of file dataMoveDtrmm.c.
References MPARTITION_D.
void arrangeDataUADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 184 of file dataMoveDtrsm.c.
References inverse4x4UpperD(), M_KERNEL_D, and MPARTITION_D.
void arrangeDataUAStrmm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 43 of file dataMoveStrmm.c.
References MPARTITION_S.
void arrangeDataUAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 184 of file dataMoveStrsm.c.
References inverse4x4UpperS(), M_KERNEL_S, and MPARTITION_S.
void arrangeDataUAZtrmm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 45 of file dataMoveZtrmm.c.
References MPARTITION_Z.
void arrangeDataUAZtrsm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 43 of file dataMoveZtrsm.c.
References M_KERNEL_Z, and MPARTITION_Z.
void arrangeDataUTACtrmm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 192 of file dataMoveCtrmm.c.
References KPARTITION_C.
void arrangeDataUTACtrsm (complex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 262 of file dataMoveCtrsm.c.
References inverse2x2Upper(), KPARTITION_C, and M_KERNEL_C.
void arrangeDataUTADtrmm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 184 of file dataMoveDtrmm.c.
References KPARTITION_D.
void arrangeDataUTADtrsm (double *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 307 of file dataMoveDtrsm.c.
References inverse4x4UpperD(), KPARTITION_D, and M_KERNEL_D.
void arrangeDataUTAStrmm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 184 of file dataMoveStrmm.c.
References KPARTITION_S.
void arrangeDataUTAStrsm (real *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 307 of file dataMoveStrsm.c.
References inverse4x4UpperS(), KPARTITION_S, and M_KERNEL_S.
void arrangeDataUTAZtrmm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 192 of file dataMoveZtrmm.c.
References KPARTITION_Z.
void arrangeDataUTAZtrsm (doublecomplex *restrict ptrA, int kLoc, int mCnt, int kCnt, int flagDiagisU)
zero out lower part of A moved to internal memory (size MPARTITION by KPARTITION) for upper triangular A. This function also sets diagonal elements to unity if necessary. This function is used to properly properly arrange A in L2 memory for upper triangular A when the transpose of C is calculated.
Parameters:
[in,out] ptrA pointer to A
[in] kLoc location of start of triangular part; zero means upper left; positive value shows offset on the upper side negative value indicate offset on the left side
[in] mCnt number of rows in A
[in] kCnt number of columns in A
[in] flagDiagisU flag to indicate if A is unit triangular or not
Definition at line 208 of file dataMoveZtrsm.c.
References KPARTITION_Z, and M_KERNEL_Z.
void dataMoveACgemm (complex *restrict dst, complex *restrict src, int m, int k, int mPartition)
Move and re-arrange A as needed by kernel for cgemm. src point to A. dst will have blocks of A, each block arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] m number of rows to move
[in] k number of columns to move
[in] mPartition number of elements in each row
Definition at line 114 of file dataMoveCgemm.c.
References KPARTITION_C.
void dataMoveADgemm (double *restrict dst, double *restrict src, int m, int k, int mPartition)
Move and re-arrange A as needed by kernel for dgemm. src point to A. dst will have blocks of A, each block arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] m number of rows to move
[in] k number of columns to move
[in] mPartition number of elements in each row
Definition at line 118 of file dataMoveDgemm.c.
References KPARTITION_D.
void dataMoveAHCgemm (complex *restrict dst, complex *restrict src, int m, int k, int kPartition)
Move and re-arrange A-Hermitian as needed by kernel for cgemm. src point to A-Hermitian. dst will have blocks of A, each block arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] m number of rows to move
[in] k number of columns to move
[in] kPartition number of elements in each column
Definition at line 183 of file dataMoveCgemm.c.
References KPARTITION_C.
void dataMoveAHZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int m, int k, int kPartition)
Move and re-arrange A-Hermitian as needed by kernel for zgemm. src point to A-Hermitian. dst will have blocks of A, each block arranged in 2 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] m number of rows to move
[in] k number of columns to move
[in] kPartition number of elements in each column
Definition at line 139 of file dataMoveZgemm.c.
References KPARTITION_Z.
void dataMoveASgemm (real *restrict dst, real *restrict src, int m, int k, int mPartition)
Move and re-arrange A as needed by kernel for sgemm. src point to A. dst will have blocks of A, each block arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] m number of rows to move
[in] k number of columns to move
[in] mPartition number of elements in each row
Definition at line 147 of file dataMoveSgemm.c.
References KPARTITION_S.
void dataMoveATCgemm (complex *restrict dst, complex *restrict src, int m, int k, int kPartition)
Move and re-arrange A' as needed by kernel for cgemm. src point to A'. dst will have blocks of A, each block arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] m number of rows to move
[in] k number of columns to move
[in] kPartition number of elements in each column
Definition at line 149 of file dataMoveCgemm.c.
References KPARTITION_C.
void dataMoveATDgemm (double *restrict dst, double *restrict src, int m, int k, int kPartition)
Move and re-arrange A' as needed by kernel for dgemm. src point to A'. dst will have blocks of A, each block arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] m number of rows to move
[in] k number of columns to move
[in] kPartition number of elements in each column
Definition at line 156 of file dataMoveDgemm.c.
References KPARTITION_D.
void dataMoveATSgemm (real *restrict dst, real *restrict src, int m, int k, int kPartition)
Move and re-arrange A' as needed by kernel for sgemm. src point to A'. dst will have blocks of A, each block arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] m number of rows to move
[in] k number of columns to move
[in] kPartition number of elements in each column
Definition at line 185 of file dataMoveSgemm.c.
References KPARTITION_S.
void dataMoveATZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int m, int k, int kPartition)
Move and re-arrange A' as needed by kernel for zgemm. src point to A'. dst will have blocks of A, each block arranged in 2 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] m number of rows to move
[in] k number of columns to move
[in] kPartition number of elements in each column
Definition at line 118 of file dataMoveZgemm.c.
References KPARTITION_Z.
void dataMoveAZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int m, int k, int mPartition)
Move and re-arrange A as needed by kernel for zgemm. src point to A. dst will have blocks of A, each block arranged in 2 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] m number of rows to move
[in] k number of columns to move
[in] mPartition number of elements in each row
Definition at line 95 of file dataMoveZgemm.c.
References KPARTITION_Z.
void dataMoveBCgemm (complex *restrict dst, complex *restrict src, int k)
Move and re-arrange B as needed by kernel for cgemm. src point to B. dst will have B arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] k number of columns to move
Definition at line 89 of file dataMoveCgemm.c.
References KPARTITION_C.
void dataMoveBDgemm (double *restrict dst, double *restrict src, int k)
Move and re-arrange B as needed by kernel for dgemm. src point to B. dst will have B arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] k number of columns to move
Definition at line 67 of file dataMoveDgemm.c.
References KPARTITION_D, and N_KERNEL_D.
void dataMoveBHCgemm (complex *restrict dst, complex *restrict src, int k)
Move and re-arrange B-Hermitian as needed by kernel for cgemm. src point to B-Hermitian. dst will have B arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] k number of columns to move
Definition at line 44 of file dataMoveCgemm.c.
References NPARTITION_C.
void dataMoveBHZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int k)
Move and re-arrange B-Hermitian as needed by kernel for zgemm. src point to B-Hermitian. dst will have B arranged in 2 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] k number of columns to move
Definition at line 43 of file dataMoveZgemm.c.
References NPARTITION_Z.
void dataMoveBSgemm (real *restrict dst, real *restrict src, int k)
Move and re-arrange B as needed by kernel for sgemm. src point to B. dst will have B arranged in 8 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] k number of columns to move
Definition at line 71 of file dataMoveSgemm.c.
References KPARTITION_S, and N_KERNEL_S.
void dataMoveBTCgemm (complex *restrict dst, complex *restrict src, int k)
Move and re-arrange B' as needed by kernel for cgemm. src point to B'. dst will have B arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] k number of columns to move
Definition at line 69 of file dataMoveCgemm.c.
References NPARTITION_C.
void dataMoveBTDgemm (double *restrict dst, double *restrict src, int k)
Move and re-arrange B' as needed by kernel for dgemm. src point to B'. dst will have B arranged in 4 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] k number of columns to move
Definition at line 43 of file dataMoveDgemm.c.
References N_KERNEL_D, and NPARTITION_D.
void dataMoveBTSgemm (real *restrict dst, real *restrict src, int k)
Move and re-arrange B' as needed by kernel for sgemm. src point to B'. dst will have B arranged in 8 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] k number of columns to move
Definition at line 43 of file dataMoveSgemm.c.
References N_KERNEL_S, and NPARTITION_S.
void dataMoveBTZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int k)
Move and re-arrange B' as needed by kernel for zgemm. src point to B'. dst will have B arranged in 2 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] k number of columns to move
Definition at line 61 of file dataMoveZgemm.c.
References NPARTITION_Z.
void dataMoveBZgemm (doublecomplex *restrict dst, doublecomplex *restrict src, int k)
Move and re-arrange B as needed by kernel for zgemm. src point to B. dst will have B arranged in 2 x k (column major)
Parameters:
[in] dst pointer to destination address
[in] src pointer to source address
[in] k number of columns to move
Definition at line 79 of file dataMoveZgemm.c.
void dataMoveLChemm (complex *restrict src, int m, int ld)
Flip a lower triangular to create Hermitian upper part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 43 of file dataMoveChemm.c.
void dataMoveLCsymm (complex *restrict src, int m, int ld)
Flip a lower triangular to create symmetric upper part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 43 of file dataMoveCsymm.c.
void dataMoveLDsymm (double *restrict src, int m, int ld)
Flip a lower triangular to create symmetric upper part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 42 of file dataMoveDsymm.c.
void dataMoveLSsymm (real *restrict src, int m, int ld)
Flip a lower triangular to create symmetric upper part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 42 of file dataMoveSsymm.c.
void dataMoveLZhemm (doublecomplex *restrict src, int m, int ld)
Flip a lower triangular to create Hermitian upper part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 42 of file dataMoveZhemm.c.
void dataMoveLZsymm (doublecomplex *restrict src, int m, int ld)
Flip a lower triangular to create symmetric upper part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 42 of file dataMoveZsymm.c.
void dataMoveUChemm (complex *restrict src, int m, int ld)
MFlip an upper triangular to create Hermitian lower part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 59 of file dataMoveChemm.c.
void dataMoveUCsymm (complex *restrict src, int m, int ld)
MFlip an upper triangular to create symmetric lower part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 57 of file dataMoveCsymm.c.
void dataMoveUDsymm (double *restrict src, int m, int ld)
MFlip an upper triangular to create symmetric lower part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 54 of file dataMoveDsymm.c.
void dataMoveUSsymm (real *restrict src, int m, int ld)
MFlip an upper triangular to create symmetric lower part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 54 of file dataMoveSsymm.c.
void dataMoveUZhemm (doublecomplex *restrict src, int m, int ld)
MFlip an upper triangular to create Hermitian lower part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 59 of file dataMoveZhemm.c.
void dataMoveUZsymm (doublecomplex *restrict src, int m, int ld)
MFlip an upper triangular to create symmetric lower part.
Parameters:
[in] src pointer to source address
[in] m number of rows/columns to flip
[in] ld number of elements in each row
Definition at line 59 of file dataMoveZsymm.c.
Copyright 2012, Texas Instruments Incorporated