BLAS Level 3: util
util
Defines
#define EDMA_CHANNELS 3
Functions
EDMA3_DRV_Result edmaInit (void)
initilizes edma transfer for
EDMA3_DRV_Result edmaWait4Completion (const int chCnt)
waits for completion of edma transfer on given channel
EDMA3_DRV_Result edmaInitiateXfer (const void *dst, const void *src, const int aCnt, const int bCnt, const int cCnt, const int srcBidx, const int destBidx, const int srcCidx, const int destCidx, const int chCnt, const int flagXfer)
initiates a new transfer
EDMA3_DRV_Result edmaClose (void)
initilizes closes and releases all edma channels for
void edmaLinkXfer ()
links channel 0 to channel 2
void edmaUnLinkXfer ()
removes link between channel 0 and channel 2
Ptr Memory_allocMSMC (SizeT size, SizeT align)
allocates memory from specific MSMC heaps for this core
Void Memory_freeMSMC (Ptr block, SizeT size)
frees previously allocated memory from specific MSMC heaps for this core
void touch (const void *array, int length)
touches an array to bring it into cache
Define Documentation
#define EDMA_CHANNELS 3
Definition at line 55 of file edma.h.
Referenced by edmaClose(), and edmaInit().
Function Documentation
EDMA3_DRV_Result edmaClose (void)
initilizes closes and releases all edma channels for
!
Definition at line 226 of file edma.c.
References EDMA_CHANNELS, gHEdma, and NUM_CORES.
Referenced by testLoop().
EDMA3_DRV_Result edmaInit (void)
initilizes edma transfer for
Definition at line 86 of file edma.c.
References BASE_CH, _EdmaXfer_::chId, EDMA_CHANNELS, gHEdma, NUM_CORES, OPT_ITCCHEN_SHIFT, OPT_ITCINTEN_SHIFT, OPT_SYNCDIM_SHIFT, OPT_TCC_MASK, OPT_TCC_SHIFT, OPT_TCCHEN_SHIFT, OPT_TCINTEN_SHIFT, _EdmaXfer_::paramSet, and _EdmaXfer_::tcc.
Referenced by testLoop().
EDMA3_DRV_Result edmaInitiateXfer (const void * dst, const void * src, const int aCnt, const int bCnt, const int cCnt, const int srcBidx, const int destBidx, const int srcCidx, const int destCidx, const int chCnt, const int flagXfer)
initiates a new transfer
Parameters:
[in] dst destination address
[in] src source address
[in] aCnt number of element (bytes) to transfer in 1st dimension
[in] bCnt number of elements to transfer in 2nd dimension
[in] cCnt number of elements to transfer in 3rd dimension
[in] srcBidx source address increment in bytes for 1st dimension
[in] destBidx destination address increment in bytes for 1st dimension
[in] srcCidx source address increment in bytes for 2nd dimension
[in] destCidx destination address increment in bytes for 2nd dimension
[in] chCnt channel number on which the transfer is to be initiated
[in] flagXfer flag to indicate if a immediate transfer is to be initiated on this channel
Definition at line 178 of file edma.c.
References determineProcId(), getGlobalAddr(), gHEdma, and _EdmaXfer_::paramSet.
void edmaLinkXfer ()
links channel 0 to channel 2
!
Definition at line 262 of file edma.c.
References determineProcId(), gHEdma, OPT_ITCCHEN_SHIFT, OPT_ITCINTEN_SHIFT, OPT_SYNCDIM_SHIFT, OPT_TCC_MASK, OPT_TCC_SHIFT, OPT_TCCHEN_SHIFT, OPT_TCINTEN_SHIFT, _EdmaXfer_::paramSet, and _EdmaXfer_::tcc.
void edmaUnLinkXfer ()
removes link between channel 0 and channel 2
!
Definition at line 304 of file edma.c.
References determineProcId(), gHEdma, OPT_ITCCHEN_SHIFT, OPT_ITCINTEN_SHIFT, OPT_SYNCDIM_SHIFT, OPT_TCC_MASK, OPT_TCC_SHIFT, OPT_TCCHEN_SHIFT, OPT_TCINTEN_SHIFT, _EdmaXfer_::paramSet, and _EdmaXfer_::tcc.
EDMA3_DRV_Result edmaWait4Completion (const int chCnt)
waits for completion of edma transfer on given channel
Parameters:
[in] chCnt channel number on which the transfer is initiated
Definition at line 250 of file edma.c.
References _EdmaXfer_::chId, determineProcId(), and gHEdma.
Ptr Memory_allocMSMC (SizeT size, SizeT align)
allocates memory from specific MSMC heaps for this core
Parameters:
[in] size size of the memory to allocate
[in] align alignment of the allocated memory
Returns:
address of allocated memory
Definition at line 46 of file memory.c.
References omp_get_thread_num().
Void Memory_freeMSMC (Ptr block, SizeT size)
frees previously allocated memory from specific MSMC heaps for this core
Parameters:
[in] block Pointer of memory block to free
[in] size size of the memory to free
Definition at line 90 of file memory.c.
References omp_get_thread_num().
void touch (const void * array, int length)
touches an array to bring it into cache
Parameters:
[in] array Pointer to array to touch
[in] length Length array in bytes
Copyright 2012, Texas Instruments Incorporated