BLAS Level 3: testBlas3.c File Reference
testBlas3.c File Reference
Test bench. This is used to test BLAS Level 3 API.
#include "string.h"
#include <ti/sysbios/BIOS.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/knl/Thread.h>
#include "defC66.h"
#include "paramBlas3.h"
#include "xgemm/testSgemm.h"
#include "xgemm/testDgemm.h"
#include "xgemm/testCgemm.h"
#include "xgemm/testZgemm.h"
#include "xsymm/testSsymm.h"
#include "xsymm/testDsymm.h"
#include "xsymm/testCsymm.h"
#include "xsymm/testZsymm.h"
#include "xhemm/testChemm.h"
#include "xhemm/testZhemm.h"
#include "xsyrk/testSsyrk.h"
#include "xsyrk/testDsyrk.h"
#include "xsyrk/testCsyrk.h"
#include "xsyrk/testZsyrk.h"
#include "xherk/testCherk.h"
#include "xherk/testZherk.h"
#include "xsyr2k/testSsyr2k.h"
#include "xsyr2k/testDsyr2k.h"
#include "xsyr2k/testCsyr2k.h"
#include "xsyr2k/testZsyr2k.h"
#include "xher2k/testCher2k.h"
#include "xher2k/testZher2k.h"
#include "xtrmm/testStrmm.h"
#include "xtrmm/testDtrmm.h"
#include "xtrmm/testCtrmm.h"
#include "xtrmm/testZtrmm.h"
#include "xtrsm/testStrsm.h"
#include "xtrsm/testDtrsm.h"
#include "xtrsm/testCtrsm.h"
#include "xtrsm/testZtrsm.h"
#include "../../src/util/edma.h"
#include <ti/csl/csl_xmcAux.h>
#include <ti/csl/csl_cacheAux.h>
Defines
#define NUM_THREADS 8
number of threads to run
#define MPAX_INDEX 3
Functions
void testLoop (void)
Void main (Int argc, String argv[])
void initSystem (void)
int omp_get_thread_num (void)
Variables
static String mainStart = "testLoop"
char testName [100]
char fileName [100]
char sLineTest [MAX_LINE_LEN]
char paramStTest [MAX_LINE_LEN]
Detailed Description
Test bench. This is used to test BLAS Level 3 API.
Definition in file testBlas3.c.
Define Documentation
#define MPAX_INDEX 3
Definition at line 384 of file testBlas3.c.
Referenced by initSystem().
#define NUM_THREADS 8
number of threads to run
Definition at line 102 of file testBlas3.c.
Referenced by testLoop().
Function Documentation
void initSystem (void)
Definition at line 388 of file testBlas3.c.
References MPAX_INDEX.
Void main (Int argc, String argv[])
Definition at line 365 of file testBlas3.c.
References mainStart, and testLoop().
int omp_get_thread_num (void)
Definition at line 420 of file testBlas3.c.
Referenced by Memory_allocMSMC(), and Memory_freeMSMC().
void testLoop (void)
Definition at line 113 of file testBlas3.c.
References _ParamsBlas3_::blas3Api, edmaClose(), edmaInit(), fileName, MAX_LINE_LEN, NUM_THREADS, paramStTest, readAPIparams(), sLineTest, testCgemm(), testChemm(), testCher2k(), testCherk(), testCsymm(), testCsyr2k(), testCsyrk(), testCtrmm(), testCtrsm(), testDgemm(), testDsymm(), testDsyr2k(), testDsyrk(), testDtrmm(), testDtrsm(), testName, testSgemm(), testSsymm(), testSsyr2k(), testSsyrk(), testStrmm(), testStrsm(), testZgemm(), testZhemm(), testZher2k(), testZherk(), testZsymm(), testZsyr2k(), testZsyrk(), testZtrmm(), testZtrsm(), and writeAPIparams().
Referenced by main().
Variable Documentation
char fileName[100]
Definition at line 97 of file testBlas3.c.
Referenced by testLoop().
String mainStart = "testLoop" [static]
Definition at line 51 of file testBlas3.c.
Referenced by main().
char paramStTest[MAX_LINE_LEN]
Definition at line 107 of file testBlas3.c.
Referenced by testLoop().
char sLineTest[MAX_LINE_LEN]
Definition at line 105 of file testBlas3.c.
Referenced by testLoop().
char testName[100]
Definition at line 97 of file testBlas3.c.
Referenced by testLoop().
Copyright 2012, Texas Instruments Incorporated