src/local_average.obj: ../src/local_average.c
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/stdio.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/linkage.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/stdarg.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/stdlib.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/time.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/math.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/float.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/access.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/elfnames.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/mathf.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/unaccess.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/mathl.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/unaccess.h
src/local_average.obj: /opt/ti/omp_1_02_00_05/packages/ti/omp/omp.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Timestamp.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/std.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/stdarg.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/stddef.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/ti/targets/elf/std.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/ti/targets/elf/C66.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/ti/targets/std.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/stdint.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/xdc.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types__prologue.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/package/package.defs.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types__epilogue.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/ITimestampClient.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IHeap.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IInstance.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Memory.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IHeap.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Error.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Error__prologue.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Main.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IGateProvider.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IInstance.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/package/Main_Module_GateProxy.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IInstance.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IGateProvider.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Error__epilogue.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/package/Memory_HeapProxy.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IInstance.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IHeap.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Error.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Error.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/ITimestampProvider.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/ITimestampClient.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/package/Timestamp_SupportProxy.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/ITimestampProvider.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/package/Timestamp_SupportProxy.h
src/local_average.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/c6x.h
src/local_average.obj: /opt/ti/C6000CGT7.4.2/include/vect.h
