/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-y30
 */

#ifndef ti_omp_navigator_Navigator__INTERNAL__
#define ti_omp_navigator_Navigator__INTERNAL__

#ifndef ti_omp_navigator_Navigator__internalaccess
#define ti_omp_navigator_Navigator__internalaccess
#endif

#include <ti/omp/navigator/Navigator.h>

#undef xdc_FILE__
#ifndef xdc_FILE
#define xdc_FILE__ NULL
#else
#define xdc_FILE__ xdc_FILE
#endif

/* init_Navigator */
#undef ti_omp_navigator_Navigator_init_Navigator
#define ti_omp_navigator_Navigator_init_Navigator ti_omp_navigator_Navigator_init_Navigator__F

/* queue_pop_elem */
#undef ti_omp_navigator_Navigator_queue_pop_elem
#define ti_omp_navigator_Navigator_queue_pop_elem ti_omp_navigator_Navigator_queue_pop_elem__F

/* queue_pop_elem_wait */
#undef ti_omp_navigator_Navigator_queue_pop_elem_wait
#define ti_omp_navigator_Navigator_queue_pop_elem_wait ti_omp_navigator_Navigator_queue_pop_elem_wait__F

/* Queue_get_num_elem */
#undef ti_omp_navigator_Navigator_Queue_get_num_elem
#define ti_omp_navigator_Navigator_Queue_get_num_elem ti_omp_navigator_Navigator_Queue_get_num_elem__F

/* queue_push_elem */
#undef ti_omp_navigator_Navigator_queue_push_elem
#define ti_omp_navigator_Navigator_queue_push_elem ti_omp_navigator_Navigator_queue_push_elem__F

/* Barrier_wait */
#undef ti_omp_navigator_Navigator_Barrier_wait
#define ti_omp_navigator_Navigator_Barrier_wait ti_omp_navigator_Navigator_Barrier_wait__F

/* Queue_Barrier_wait */
#undef ti_omp_navigator_Navigator_Queue_Barrier_wait
#define ti_omp_navigator_Navigator_Queue_Barrier_wait ti_omp_navigator_Navigator_Queue_Barrier_wait__F

/* wait_for_release */
#undef ti_omp_navigator_Navigator_wait_for_release
#define ti_omp_navigator_Navigator_wait_for_release ti_omp_navigator_Navigator_wait_for_release__F

/* wait_threads_release */
#undef ti_omp_navigator_Navigator_wait_threads_release
#define ti_omp_navigator_Navigator_wait_threads_release ti_omp_navigator_Navigator_wait_threads_release__F

/* Close_Queue */
#undef ti_omp_navigator_Navigator_Close_Queue
#define ti_omp_navigator_Navigator_Close_Queue ti_omp_navigator_Navigator_Close_Queue__F

/* sysExit */
#undef ti_omp_navigator_Navigator_sysExit
#define ti_omp_navigator_Navigator_sysExit ti_omp_navigator_Navigator_sysExit__F

/* Create_Queue */
#undef ti_omp_navigator_Navigator_Create_Queue
#define ti_omp_navigator_Navigator_Create_Queue ti_omp_navigator_Navigator_Create_Queue__F

/* Module_startup */
#undef ti_omp_navigator_Navigator_Module_startup
#define ti_omp_navigator_Navigator_Module_startup ti_omp_navigator_Navigator_Module_startup__F

/* Instance_init */
#undef ti_omp_navigator_Navigator_Instance_init
#define ti_omp_navigator_Navigator_Instance_init ti_omp_navigator_Navigator_Instance_init__F

/* Instance_finalize */
#undef ti_omp_navigator_Navigator_Instance_finalize
#define ti_omp_navigator_Navigator_Instance_finalize ti_omp_navigator_Navigator_Instance_finalize__F

/* per-module runtime symbols */
#undef Module__MID
#define Module__MID ti_omp_navigator_Navigator_Module__id__C
#undef Module__DGSINCL
#define Module__DGSINCL ti_omp_navigator_Navigator_Module__diagsIncluded__C
#undef Module__DGSENAB
#define Module__DGSENAB ti_omp_navigator_Navigator_Module__diagsEnabled__C
#undef Module__DGSMASK
#define Module__DGSMASK ti_omp_navigator_Navigator_Module__diagsMask__C
#undef Module__LOGDEF
#define Module__LOGDEF ti_omp_navigator_Navigator_Module__loggerDefined__C
#undef Module__LOGOBJ
#define Module__LOGOBJ ti_omp_navigator_Navigator_Module__loggerObj__C
#undef Module__LOGFXN0
#define Module__LOGFXN0 ti_omp_navigator_Navigator_Module__loggerFxn0__C
#undef Module__LOGFXN1
#define Module__LOGFXN1 ti_omp_navigator_Navigator_Module__loggerFxn1__C
#undef Module__LOGFXN2
#define Module__LOGFXN2 ti_omp_navigator_Navigator_Module__loggerFxn2__C
#undef Module__LOGFXN4
#define Module__LOGFXN4 ti_omp_navigator_Navigator_Module__loggerFxn4__C
#undef Module__LOGFXN8
#define Module__LOGFXN8 ti_omp_navigator_Navigator_Module__loggerFxn8__C
#undef Module__G_OBJ
#define Module__G_OBJ ti_omp_navigator_Navigator_Module__gateObj__C
#undef Module__G_PRMS
#define Module__G_PRMS ti_omp_navigator_Navigator_Module__gatePrms__C
#undef Module__GP_create
#define Module__GP_create ti_omp_navigator_Navigator_Module_GateProxy_create
#undef Module__GP_delete
#define Module__GP_delete ti_omp_navigator_Navigator_Module_GateProxy_delete
#undef Module__GP_enter
#define Module__GP_enter ti_omp_navigator_Navigator_Module_GateProxy_enter
#undef Module__GP_leave
#define Module__GP_leave ti_omp_navigator_Navigator_Module_GateProxy_leave
#undef Module__GP_query
#define Module__GP_query ti_omp_navigator_Navigator_Module_GateProxy_query


#endif /* ti_omp_navigator_Navigator__INTERNAL____ */
