names={ ...
    'sgemm_verification_omp' ...
    'cgemm_verification_omp' ...
    'ssymm_verification_omp' ...
    'csymm_verification_omp' ...
    'chemm_verification_omp' ...
    'ssyrk_verification_omp' ...
    'csyrk_verification_omp' ...
    'cherk_verification_omp' ...
    'ssyr2k_verification_omp' ...
    'csyr2k_verification_omp' ...
    'cher2k_verification_omp' ...
    'strmm_verification_omp' ...
    'ctrmm_verification_omp' ...
    'strsm_verification_omp' ...
    'ctrsm_verification_omp' ...
};

for cnt=1:length(names),
    filename=sprintf('params/blas3_results_%s.txt',names{cnt});
    disp(sprintf('analyzing.... %s',filename)); 
    
    fid=fopen(filename,'r');
    while 1
        tline = fgetl(fid);
        if ~ischar(tline) break; end;
        v=sscanf(tline,'%f');
        if(v(1) > 1.0e-2) disp(tline); end;
    end
    fclose(fid);
    
end;

names={ ...
    'dgemm_verification_omp' ...
    'zgemm_verification_omp' ...
    'dsymm_verification_omp' ...
    'zsymm_verification_omp' ...
    'zhemm_verification_omp' ...
    'dsyrk_verification_omp' ...
    'zsyrk_verification_omp' ...
    'zherk_verification_omp' ...
    'dsyr2k_verification_omp' ...
    'zsyr2k_verification_omp' ...
    'zher2k_verification_omp' ...
    'dtrmm_verification_omp' ...
    'ztrmm_verification_omp' ...
    'dtrsm_verification_omp' ...
    'ztrsm_verification_omp' ...
};

for cnt=1:length(names),
    filename=sprintf('params/blas3_results_%s.txt',names{cnt});
    disp(sprintf('analyzing.... %s',filename)); 
    
    fid=fopen(filename,'r');
    while 1
        tline = fgetl(fid);
        if ~ischar(tline) break; end;
        v=sscanf(tline,'%f');
        if(v(1) > 1.0e-10) disp(tline); end;
    end
    fclose(fid);
    
end;

