/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      1000,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6670",
            customMemoryMap: [
                ["L2SRAM",   {name: "L2SRAM",    base: 0x00800000, len: 0x00100000}],
                ["DDR3",     {name: "DDR3",      base: 0x80000000, len: 0x20000000}],
                ["MSMCSRAM", {name: "MSMCSRAM",  base: 0x0C000000, len: 0x00100000}],
                ["MSMCSRAM_NOCACHE", {name: "MSMCSRAM_NOCACHE", base: 0xA0100000, len: 0x00100000}],
            ],
            l1DMode:"32k",
            l1PMode:"32k",
            l2Mode:"0k",

    });
    
instance :
    
    override config string codeMemory  = "MSMCSRAM";   
    override config string dataMemory  = "MSMCSRAM_NOCACHE";                             
    override config string stackMemory = "L2SRAM";
    
}
