src/main.obj: ../src/main.c
src/main.obj: /opt/ti/omp_1_02_00_05/packages/ti/omp/omp.h
src/main.obj: /opt/ti/C6000CGT7.4.0/include/stdio.h
src/main.obj: /opt/ti/C6000CGT7.4.0/include/linkage.h
src/main.obj: /opt/ti/C6000CGT7.4.0/include/stdarg.h
src/main.obj: /opt/ti/C6000CGT7.4.0/include/string.h
src/main.obj: /opt/ti/C6000CGT7.4.0/include/assert.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Timestamp.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/std.h
src/main.obj: /opt/ti/C6000CGT7.4.0/include/stdarg.h
src/main.obj: /opt/ti/C6000CGT7.4.0/include/stddef.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/ti/targets/elf/std.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/ti/targets/elf/C66.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/ti/targets/std.h
src/main.obj: /opt/ti/C6000CGT7.4.0/include/stdint.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/xdc.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types__prologue.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/package/package.defs.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types__epilogue.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/ITimestampClient.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IHeap.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IInstance.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Memory.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IHeap.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Error.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Error__prologue.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Main.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IGateProvider.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IInstance.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/package/Main_Module_GateProxy.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IInstance.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IGateProvider.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IModule.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Error__epilogue.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/package/Memory_HeapProxy.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IInstance.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/IHeap.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Error.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Error.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/ITimestampProvider.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/ITimestampClient.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/package/Timestamp_SupportProxy.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/Types.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/ITimestampProvider.h
src/main.obj: /opt/ti/xdctools_3_24_05_48/packages/xdc/runtime/package/Timestamp_SupportProxy.h
